######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 19 11:36:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += script

CONFIG += qdbus

# Input
HEADERS += bot.h
SOURCES += bot.cpp main.cpp
